### ISSUE TITLE
cert manager working, but getting ''404 page not found" only in HTTPS

### ISSUE THREAD

**Issue by guysoft** [mmatur/traefik-cert-manager#4]
Hey,
I have cert-manager set up and working (I am getting valid Let't encrypt certificates). But the `https://`` page displays: ``404 page not found``.

The plain ``http://`` works fine.

Here is the issuer.yaml:

```
   apiVersion: cert-manager.io/v1alpha2
   kind: Issuer
   metadata:
     name: letsencrypt-prod
     namespace: default
   spec:
     acme:
       # The ACME server URL
       server: https://acme-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
       email: admin@shapedo.com
       # Name of a secret used to store the ACME account private key
       privateKeySecretRef:
         name: letsencrypt-prod
       # Enable the HTTP-01 challenge provider
       solvers:
       - http01:
           ingress:
             class: traefik-cert-manager
```

cert-manager on EKS set up with the following commands:
```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.14.1/cert-manager.crds.yaml


# Create the namespace for cert-manager
kubectl create namespace cert-manager

#kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.14.0/cert-manager.yaml
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.14.1/cert-manager.yaml

helm3 install \
  cert-manager \
  --namespace cert-manager \
  --version v0.14.1 \
  jetstack/cert-manager
```
Kubernets 0.15

How can I debug this?
