### ISSUE TITLE
traefikservices.traefik.containo.us is missing in 01-crd.yaml

### ISSUE THREAD

**Issue by guysoft** [mmatur/traefik-cert-manager#6]
Gives error:
```
E0423 14:42:44.085981 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.TraefikService: the server could not find the requested resource (get traefikservices.traefik.containo.us)
```

Workaround, apply:
```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traefikservices.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TraefikService
    plural: traefikservices
    singular: traefikservice
  scope: Namespaced
```
source: https://docs.traefik.io/reference/dynamic-configuration/kubernetes-crd/
