### ISSUE TITLE
Moving traefik to install via helm means your service gets re-created

### ISSUE THREAD

**Issue by guysoft** [mmatur/traefik-cert-manager#9]
Hey, 
Saw you moved the installation to work via helm.

The issue with this is that when you what to change the configuration of traefik you also need to reinstall the service, which means you will get a different node balancer and you will need to set up all your DNS over again.

I suggest you do provide a non-helm way to install it too.
I use helm for many things, but not the ingress set up.

**Comment by mmatur** [comment]
Hey,

You can use the following command to upgrade the your helm installation.

```
helm upgrade traefik traefik/traefik --values values.yaml
```

**Comment by guysoft** [comment]
eh, think I am forking in that case. Seems to work for me. But might change my mind, at the moment there are lots of moving parts in in the project, that chart is new. I see no value in holding this in helm. The cert-manager yes. But not Traefik. I am also open to other suggestions if you have any.

**Comment by guysoft** [comment]
For example here is my deployment looks it handles anti-afinity now so traefik is high-avilability, helm AFAIK makes this more complicated to set up:
```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/name: traefik
  namespace: traefik
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
        app: traefik
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - traefik
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/traefik
      volumes:
        - name: config-volume
          configMap:
            name: traefik-config
```

**Comment by mmatur** [comment]
To manage the affinity you just have to add the following in your `values.yaml`

```yaml
affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - traefik
```

I will keep the helm chart for my example. I will close this issue because the question is answered.
